# Generated by Django 5.2.6 on 2025-11-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_customuser_is_vip_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
