# Generated by Django 5.2.6 on 2025-12-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_customuser_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'default'), ('VIP', 'vip')], default='DEFAULT', max_length=15),
        ),
    ]
