# Generated by Django 5.2.6 on 2025-12-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_emailverification'),
        ('users_app', '0004_remove_customuser_is_default_and_more'),
    ]

    operations = [
    ]
