# Generated by Django 5.2.6 on 2025-12-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_merge_20251215_1023'),
        ('users_app', '0005_merge_20251215_1039'),
    ]

    operations = [
    ]
