# Generated by Django 5.2.6 on 2025-12-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencyprice',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cryptocurrencyprice',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='cryptocurrencyprice',
            name='yesterday_price',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
    ]
