# Generated by Django 5.2.6 on 2025-12-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_crypto_app', '0002_alter_cryptocurrencyprice_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencyprice',
            name='price',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='cryptocurrencyprice',
            name='yesterday_price',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
    ]
